import { promises as fs } from 'node:fs';
import path from 'node:path';

import { UserError } from '../../utils/errors.js';

const AGENT_PROVIDERS = new Set(['claude', 'gemini', 'codex']);

export type InitOptions = {
  agent?: string;
  force?: boolean;
};

const buildTemplate = (projectName: string, provider: string): string => `# watchfix.yaml
# Generated by watchfix init

project:
  name: ${projectName}
  root: .

agent:
  provider: ${provider}
  timeout: 5m
  retries: 2
  # command: ${provider}
  # args:
  #   - --model
  #   - sonnet
  #   - --dangerously-skip-permissions
  #   - -p
  # stderr_is_progress: false

logs:
  sources:
    - name: app
      type: file
      path: ./logs/app.log

  # Example docker source:
  # - name: api
  #   type: docker
  #   container: my-app-api

  # Example command source:
  # - name: compose
  #   type: command
  #   run: docker-compose logs --tail=100
  #   interval: 30s

  context_lines_before: 10
  context_lines_after: 5
  max_line_buffer: 10000

verification:
  test_commands:
    - npm run lint
    - npm test
  test_command_timeout: 5m
  health_checks:
    - http://localhost:3000/health
  health_check_timeout: 10s
  wait_after_fix: 5s

limits:
  max_attempts_per_error: 3

cleanup:
  context_max_age_days: 7
  context_max_size_kb: 256

patterns:
  match:
    - "FATAL:"
    - "panic:"
  ignore:
    - "DeprecationWarning"
    - "ExperimentalWarning"
`;

const ensureGitignore = async (cwd: string): Promise<void> => {
  const gitignorePath = path.join(cwd, '.gitignore');
  let contents = '';

  try {
    contents = await fs.readFile(gitignorePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }

  const hasEntry = contents
    .split(/\r?\n/)
    .some((line) => line.trim() === '.watchfix/');

  if (hasEntry) {
    return;
  }

  const trimmed = contents.replace(/\s+$/u, '');
  const prefix = trimmed.length > 0 ? `${trimmed}\n` : '';
  const updated = `${prefix}.watchfix/\n`;

  await fs.writeFile(gitignorePath, updated, 'utf8');
};

export const initCommand = async (options: InitOptions): Promise<void> => {
  const cwd = process.cwd();
  const configPath = path.join(cwd, 'watchfix.yaml');
  const projectName = path.basename(cwd) || 'my-project';
  const provider = (options.agent ?? 'claude').toLowerCase();

  if (!AGENT_PROVIDERS.has(provider)) {
    throw new UserError(
      `Unknown agent provider: ${options.agent ?? provider}. ` +
        'Use one of: claude, gemini, codex.'
    );
  }

  try {
    await fs.access(configPath);
    if (!options.force) {
      throw new UserError('watchfix.yaml already exists. Use --force to overwrite.');
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }

  const template = buildTemplate(projectName, provider);

  await fs.writeFile(configPath, template, 'utf8');
  await ensureGitignore(cwd);
};
